-- Supprimer les tables dépendantes d'abord pour éviter les conflits
DROP TABLE IF EXISTS Reparation_composant CASCADE;
DROP TABLE IF EXISTS Stock CASCADE;
DROP TABLE IF EXISTS Modele_composant CASCADE;
DROP TABLE IF EXISTS Reparation CASCADE;
DROP TABLE IF EXISTS Composant CASCADE;
DROP TABLE IF EXISTS Technicien CASCADE;
DROP TABLE IF EXISTS Ordinateur CASCADE;
DROP TABLE IF EXISTS Modele CASCADE;
DROP TABLE IF EXISTS Client CASCADE;
DROP TABLE IF EXISTS Marque CASCADE;
DROP TABLE IF EXISTS Type_composant CASCADE;
